{% set name = "mujs" %}
{% set version = "1.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://mujs.com/downloads/{{ name }}-{{ version }}.tar.gz
  sha256: 506d34882f2620a2fdeb6db63dbb7a8ffd98f417689d8f3c84f2feac275e39a9
  patches:
    - patches/0001-fix-python-alias.patch
    - patches/make.patch  # [linux]
    - patches/windows.patch  # [win]

build:
  number: 2

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make             # [not win]
    - msys2-make       # [win]
    - msys2-coreutils  # [win]
    - cmake            # [win]
    - ninja-base       # [win]
    - python  # Needed for dynamic python header generation
  host:
    - readline {{ readline }}     # [not win]
 
test:
  commands:
    - touch test.c && mujs -s test.c  # [not win]
    - type nul >test.c && mujs -s test.c  # [win]

about:
  home: https://mujs.com
  license: ISC
  license_family: Other
  license_file: COPYING
  summary: 'MuJS is a lightweight Javascript interpreter designed for embedding in other software to extend them with scripting capabilities.'
  description: |
    MuJS was designed with a focus on small size, correctness, and simplicity.
    It is written in portable C and implements ECMAScript as specified by ECMA-262.
    The interface for binding with native code is designed to be as simple as 
    possible to use, and is very similar to Lua. There is no need to interact with 
    byzantine C++ template mechanisms, or worry about marking and unmarking garbage 
    collection roots, or wrestle with obscure build systems.
  doc_url: https://mujs.com/reference.html
  dev_url: https://git.ghostscript.com/?p=mujs.git

extra:
  recipe-maintainers:
    - jan-janssen
